name: ci

on: push
  # push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_REPOSITORY: "$DOCKER_REGISTRY/${{ github.repository }}"
  DOCKER_IMAGE_TAG: "${{ github.sha }}"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  build:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - name: Get env vars
      run: ${DOCKER_IMAGE_REPOSITORY} && env
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Check docker and buildx versions
      run: docker version && docker buildx version
    - name: Build the Docker image
      run: |
        docker buildx create --use
        docker buildx bake --push

  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          trivy-config: trivy.yaml
      - name: Run Trivy vulnerability scanner in config mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "."
          trivy-config: trivy.yaml
          ignore-unfixed: true
  
  trivy-docker:
    name: Trivy Scan Docker
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.DOCKER_IMAGE_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}"
          format: "table"
          vuln-type: "os,library"
          # severity: "CRITICAL,HIGH"
          ignore-unfixed: true