name: ci

on: push
  # push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
      - name: Run Trivy vulnerability scanner in config mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          trivy-config: trivy.yaml

  build:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: [trivy-scan]
    steps:
    - name: Get env vars
      run: env
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Log in to the Container registry
      run: docker login -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}" ${DOCKER_REGISTRY}
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Check docker and buildx versions
      run: docker version && docker buildx version
    - name: Build the Docker image
      run: |
        docker buildx create --use
        docker buildx bake
