name: ci

on: push
  # push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_REPOSITORY: "ghcr.io/${{ github.repository }}"
  DOCKER_IMAGE_TAG: "${{ github.sha }}"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest


  build:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - name: Get env vars
      run: env
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Check docker and buildx versions
      run: docker version && docker buildx version
    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx bake --push


  # https://github.com/marketplace/actions/aqua-security-trivy
  trivy-fs:
    name: Trivy Scan FS
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          trivy-config: trivy.yaml
          ignore-unfixed: true


  trivy-config:
    name: Trivy Scan Config
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner in config mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "."
          trivy-config: trivy.yaml
          ignore-unfixed: true
  

  trivy-image:
    name: Trivy Scan Docker
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.DOCKER_IMAGE_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}"
          format: "table"
          vuln-type: "os" # os,library
          # severity: "CRITICAL,HIGH"
          ignore-unfixed: true


  dockerhub:
    name: Build and Push Docker image to DockerHub
    runs-on: ubuntu-latest
    needs:
      - trivy-fs
      - trivy-config
      - trivy-image
    env:
      DOCKER_IMAGE_REPOSITORY: "${{ github.repository }}"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx bake --push
