name: Docker Image CI

on: [push]
  # push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get env vars
      run: env
    - run: docker version && docker buildx version
    - name: Build the Docker image
      run: |
        docker buildx create --use
        docker buildx bake
