name: Base Pipeline

on: push
  # push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  build:
    runs-on: ubuntu-latest
    needs: [golangci]
    steps:
    - name: Get env vars
      run: env
    - run: docker version && docker buildx version
    - name: Build the Docker image
      run: |
        docker buildx create --use
        docker buildx bake
