name: release

on:
  release:
    types: [published]


env:
  DOCKER_IMAGE_REPOSITORY: "${{ github.repository }}"
  DOCKER_IMAGE_TAG: "${{ github.ref_name }}"


jobs:
  dockerhub-push:
    name: DockerHub Push
    runs-on: ubuntu-latest
    env:
      IS_RELEASE: "true"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Get env vars
        run: env
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx bake --push


  trivy-image:
    name: Trivy Scan Docker Image
    runs-on: ubuntu-latest
    needs: [dockerhub-push]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner (ALL)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.DOCKER_IMAGE_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}"
          format: "table"
          vuln-type: "os,library"
          ignore-unfixed: true
      - name: Run Trivy vulnerability scanner (CRITICAL)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.DOCKER_IMAGE_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}"
          format: "table"
          vuln-type: "os"
          ignore-unfixed: true
          exit-code: "1"
          severity: "CRITICAL"
